Update cloudjack.py
`sort()` breaks the script:

```
Traceback (most recent call last):
  File "/private/tmp/cloudjack/cloudjack/cloudjack.py", line 183, in <module>
    main()
  File "/private/tmp/cloudjack/cloudjack/cloudjack.py", line 90, in main
    print(route53.list_hosted_zones()['HostedZones'].sort())
TypeError: '<' not supported between instances of 'dict' and 'dict'
```